### ISSUE TITLE
Support publishing packages from other branches

### ISSUE THREAD

**Issue by bebbs** [dillonkearns/elm-publish-action#6]
I maintain a package where the default branch name is `main` instead of master, I think it may also be the github.com-wide default for new repositories now (?)

Would love to use `elm-publish-action` to automate publishing new versions, but to do that I think this action would have to support publishing packages from `main` as well as `master`? It looks like it checks for `refs/heads/master` only here:

https://github.com/dillonkearns/elm-publish-action/blob/67ef64ef2550d41c6c16550276ae2197ff5b670a/src/main.ts#L36

Would a patch to allow publishing from main / master, or a more generic solution to make it configurable be welcomed?

**Comment by dillonkearns** [comment]
Hello @bebbs! Ah yes, great point. It would be great to use the repo's default branch. There's already a feature to help with this: https://github.blog/changelog/2020-07-22-github-actions-better-support-for-alternative-default-branch-names/. So we should be able to just use `$default-branch` now instead of hardcoding the branch to `master`.

Happy to discuss more if you have any other thoughts.
